name: Open PR for Issue
on:
  pull_request:
    types: [closed]
jobs:
  openPr:
    name: Cherry Pick PR for label
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Checkout GitHub Actions
        uses: actions/checkout@v2
        with:
          repository: oskardudycz/github-actions
          token: ${{ secrets.GH_PAT }}
      - name: Cherry Pick PR for label
        uses: ./.github/actions/cherry-pick-pr-for-label
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
