name: Open PR for Issue
on:
  pull_request:
    types: [closed]
jobs:
  openPr:
    name: Cherry Pick PR for label
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: checkout GitHub actions
        uses: actions/checkout@v2
        with:
          clean: false
          repository: oskardudycz/github-actions
          persist-credentials: false
      - name: Cherry Pick PR for label
        uses: ./.github/actions/cherry-pick-pr-for-label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
